---
title: "Birthweight T2D eQTL enrichment"
output: html_document
---

```{r echo=F,message=F,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Changes from previous version


1) There is now a column `method`, indicating whether a linear model or logistic regression was used
2) For genes with multiple SNPs, the median value of `prob_Z1_conf` was used.



```{r,message=F,warning=F}
library(tidyverse)
library(drake)
# c("causedata_1L", "medz_causedata_1L", "cause_df_causedata_1L", 
# "summ_cause_med_cause_df_causedata_1L", "summ_cause_samp_cause_df_causedata_1L", 
# "genres_dfmed_1L_summ_cause_med_cause_df_causedata_1L_medz_causedata_1L", 
# "genresmed_summ_cause_med_cause_df_causedata_1L_genres_dfmed_1L_summ_cause_med_cause_df_causedata_1L_medz_causedata_1L", 
# "res_df_1L_cause_df_causedata_1L_medz_causedata_1L")
gene_summ_df <- readd("summ_cause_med_cause_df_causedata_1L")
res_df <- readd("res_df_1L_cause_df_causedata_1L_medz_causedata_1L")
gene_df <- readd("genresmed_summ_cause_med_cause_df_causedata_1L_genres_dfmed_1L_summ_cause_med_cause_df_causedata_1L_medz_causedata_1L")
loadd(godf)

sig_term_snp <- readRDS("../data/eqtl_enrichment.RDS")
df <- sig_term_snp[["egg_bw__diagram_t2d_cause"]] 

go_names <- distinct(godf,go_id,name_1006) %>% rename(GO_term=name_1006)
```


### Enriched pathways
```{r}
dplyr::filter(res_df,term!="(Intercept)",p_BH<0.05) %>% dplyr::select(-file) %>%  inner_join(go_names) %>% dplyr::select(-term) %>% 
  arrange(p_BH) %>% 
  DT::datatable()
```

### genes in enriched pathways 


```{r}
gene_df %>% DT::datatable()
```
