---
title: "Causal patterns in pairs of GWAS summary statistics"
output:
  html_document:
    toc: false
---

Research website for Sherlock2 project with Jean Morrison, Xin He, and Matthew Stephens. 

## Project updates (most recent to older)

+ 11-15-17 to 11-26-17 Working on understanding the effects of LD, possibilities of subsetting SNPS [without LD](subset_snps.html), [with LD](subset_snps.html).
+ 11-13-17 Investigation of using LD weights to approximate likelihoods and posteriors. [Summary](pseudo_likelihood.html).
+ Working on write-up of method. Link to document in progress coming.
+ 10-23-17 Added grid approximation for posterior distributions. Summary coming.
+ 10-12-17 Compared different priors in original "b-q" model. Moved away from "non-local" priors. [Summary](mh_priors2.htlml)
+ 10-5-17 (detour) Looked at estimating distributions of angles. [Summary](polar_intro.html)
+ 9-25-17 (detour) Explored the possibility of a "more symmetric" model. [Summary](mh_new_dist.html)
+ 7-22 to 9-17-17 Implemented sampling based method for fitting models which samples posteriors of b and q using MH and then compairs models using WAIC. [This summary](mh_test.html) includes method description and simulation results.

Before this we were estimating parameters by maximum likelihood. Results prior to this were based on that approach.

## First application to GWAS
+ 6-13-17 [here](gwas_ss.html) we analyze 15 traits analyzed by Pickerell et al using the two-factor model fit by ML. Also introduces new method for estimating the prior distribution of effect sizes.
+ 5-15-17 Applictaion to LDL an CAD. [Here](cad_ldl.html) we analyze the relationship between LDL cholesterol and coronary artery disease and between LDL and height using the two-factor model fit by ML.

## Early simulations
+ 5-5-17 Simulations attempting to answer the question "Can signal be driven by only one or two SNPs": [here](sims_numtop.html). Short answer: Yes but it is less likely than using the original sherlock method or the simple correlation approach
+ 5-2-17 Added a parameter to account for overlapping samples, genome-wide correlation between summary statistics. [here](simulations_v4.html)
+ 3-29-17 Comparing the orignal Sherlock method on the same simulations: [here](sherlock1.html).
+ 5-2-17 Simulations comparing the compound and correlation approaches are [here](compare_approaches.html).

## Notes from model development phase (also reverse chronological order)
+ 6-14-17 [Thoughts on a three factor model](three_factor.html)
+ 3-6-17 The two factor model is decribed [here](two_factor.html)
+ 3-6-17 Created workflowr project. Our first two approaches, the "correlation" and "compound" approach are described [here](sherlock2_compound_and_correlation.pdf)










